project:
  type: website

website:
  title: "Template quarto revealjs project"
  site-url: https://sparrow0hawk.github.io/template-revealjs-quarto
  description: "Template site for revealjs with quarto"


